namespace RaiffaisenBot.Logic.Handlers;

[Flags]
public enum HandlerMessageType : long
{
    Unknown = 1 << 0,
    Text = 1 << 1,
    Photo = 1 << 2,
    Audio = 1 << 3,
    Video = 1 << 4,
    Voice = 1 << 5,
    Document = 1 << 6,
    Sticker = 1 << 7,
    Location = 1 << 8,
    Contact = 1 << 9,
    Venue = 1 << 10,
    Game = 1 << 11,
    VideoNote = 1 << 12,
    Invoice = 1 << 13,
    SuccessfulPayment = 1 << 14,
    WebsiteConnected = 1 << 15,
    ChatMembersAdded = 1 << 16,
    ChatMemberLeft = 1 << 17,
    ChatTitleChanged = 1 << 18,
    ChatPhotoChanged = 1 << 19,
    MessagePinned = 1 << 20,
    ChatPhotoDeleted = 1 << 21,
    GroupCreated = 1 << 22,
    SupergroupCreated = 1 << 23,
    ChannelCreated = 1 << 24,
    MigratedToSupergroup = 1 << 25,
    MigratedFromGroup = 1 << 26,
    Poll = 1 << 27,
    Dice = 1 << 28,
    MessageAutoDeleteTimerChanged = 1 << 29,
    ProximityAlertTriggered = 1 << 30,
    WebAppData = 1 << 31,
    VideoChatScheduled = 1L << 32,
    VideoChatStarted = 1L << 33,
    VideoChatEnded = 1L << 34,
    VideoChatParticipantsInvited = 1L << 35,
    Animation = 1L << 36,
    ForumTopicCreated = 1L << 37,
    ForumTopicClosed = 1L << 38,
    ForumTopicReopened = 1L << 39,
    ForumTopicEdited = 1L << 40,
    GeneralForumTopicHidden = 1L << 41,
    GeneralForumTopicUnhidden = 1L << 42,
    WriteAccessAllowed = 1L << 43,
}
